SystemOrganization addCategory: #'Network-Exceptions'!
SystemOrganization addCategory: #'Network-Kernel'!
SystemOrganization addCategory: #'Network-MailSending'!
SystemOrganization addCategory: #'Network-Protocols'!
SystemOrganization addCategory: #'Network-RFC822'!
SystemOrganization addCategory: #'Network-RemoteDirectory'!
SystemOrganization addCategory: #'Network-URI'!
SystemOrganization addCategory: #'Network-UUID'!
SystemOrganization addCategory: #'Network-Url'!
SystemOrganization addCategory: #'Network-HTML-Formatter'!
SystemOrganization addCategory: #'Network-HTML-Forms'!
SystemOrganization addCategory: #'Network-HTML-Parser'!
SystemOrganization addCategory: #'Network-HTML-Parser Entities'!
SystemOrganization addCategory: #'Network-HTML-Tokenizer'!
